export const dayTheme = {
  colors: {
    primaryBg: '#FFFFFF',
    secondaryBg: 'rgba(255, 255, 255, 0.4)',
    loginPageBg: '#E7EAF2',
    primaryText: '#000000',
    secondaryText: '#BDBDBD',
    secondaryDarkText: '#A6A6A6',
    secondaryLightText: '#E0E0E0',
    primaryBtn: '#FFFFFF',
    primaryBgBtn: '#24CCA7',
    hoverBgBtn: '#2be2ba',
    secondaryBtn: '#4A56E2',
    secondaryBgBtn: 'transparent',
    primaryPasswordIndicator: '#24CCA7',
    secondaryPasswordIndicator: '#E5F1EF',
    navIconBg: '#6E78E8',
    navIconBgActive: '#4A56E2',
    expense: '#FF6596',
    basicStat: '#FED057',
    productsStat: '#FFD8D0',
    carStat: '#FD9498',
    selfStat: '#C5BAFF',
    childrenStat: '#6E78E8',
    houseStat: '#4A56E2',
    educationStat: '#81E1FF',
    leisureStat: '#24CCA7',
    otherStat: '#00AD84',
    gradient: 'linear-gradient(rgba(47, 48, 58, 0),rgba(47, 48, 58, 0))',
  },
  space: [0, 8, 12, 16, 20, 28, 36, 40, 60],
  fonts: {
    body: 'Circe-Regular, sans-serif',
    bodyBold: 'Circe-Bold, sans-serif',
    heading: 'Poppins-Regular, sans-serif',
    headingBold: 'Poppins-Bold, sans-serif',
  },
  fontSizes: {
    xs: '12px',
    s: '16px',
    m: '18px',
    l: '30px',
    xl: '40px',
  },
  fontWeights: {
    normal: 400,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
  },
  letterSpacings: {
    body: '0.1em',
  },
  borders: {
    none: 'none',
    normal: '1px solid',
  },
  radii: {
    none: '0',
    normal: '4px',
    round: '50%',
    btn: '20px',
  },
};

export const nightTheme = {
  colors: {
    primaryBg: '#38398F',
    secondaryBg: '#9B91C7',
    loginPageBg: '#685AA2',
    primaryText: '#ffffff',
    secondaryText: '#ffffff',
    secondaryDarkText: '#DAD8D8',
    secondaryLightText: '#ECEAEA',
    primaryBtn: '#FFFFFF',
    primaryBgBtn: '#24CCA7',
    hoverBgBtn: '#2be2ba',
    secondaryBtn: '#4A56E2',
    secondaryBgBtn: 'transparent',
    primaryPasswordIndicator: '#24CCA7',
    secondaryPasswordIndicator: '#E5F1EF',
    navIconBg: '#6E78E8',
    navIconBgActive: '#4A56E2',
    expense: '#FF6596',
    basicStat: '#FED057',
    productsStat: '#FFD8D0',
    carStat: '#FD9498',
    selfStat: '#C5BAFF',
    childrenStat: '#6E78E8',
    houseStat: '#4A56E2',
    educationStat: '#81E1FF',
    leisureStat: '#24CCA7',
    otherStat: '#00AD84',
    gradient: 'linear-gradient(rgba(47, 48, 58, 0.35),rgba(47, 48, 58, 0.35))',
  },
  space: [0, 8, 12, 16, 20, 28, 36, 40, 60],
  fonts: {
    body: 'Circe-Regular, sans-serif',
    bodyBold: 'Circe-Bold, sans-serif',
    heading: 'Poppins-Regular, sans-serif',
    headingBold: 'Poppins-Bold, sans-serif',
  },
  fontSizes: {
    xs: '12px',
    s: '16px',
    m: '18px',
    l: '30px',
    xl: '40px',
  },
  fontWeights: {
    normal: 400,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
  },
  letterSpacings: {
    body: '0.1em',
  },
  borders: {
    none: 'none',
    normal: '1px solid',
  },
  radii: {
    none: '0',
    normal: '4px',
    round: '50%',
    btn: '20px',
  },
};
